import os
os.startfile('C:/Users/parth/OneDrive/Desktop/pbs_backup/restore.py')
print("Successful")